# escape=`

# Use the latest Windows Server Core image with .NET Framework 4.7.2.
FROM mcr.microsoft.com/windows/servercore:ltsc2019@sha256:ab693245cc2f6c018a5718b9ded9eac109629e207907df81991f449d138cd85c

LABEL maintainer="Michael Kriese <michael.kriese@visualon.de>" `
  org.opencontainers.image.authors="VisualOn GmbH <code@visualon.de>" `
  org.opencontainers.image.source="https://github.com/visualon/docker-buildpack" `
  org.opencontainers.image.url="https://github.com/visualon/docker-buildpack"

ENV `
  POWERSHELL_TELEMETRY_OPTOUT=1 `
  DOTNET_CLI_TELEMETRY_OPTOUT=1 `
  DOTNET_CLI_UI_LANGUAGE=en-us `
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1

COPY src\ c:\

RUN c:\tools\init.cmd

# renovate: datasource=github-releases lookupName=kiennq/scoop-better-shimexe versioning=gradle
RUN install-tool shim 2.2.1

# renovate: datasource=github-releases lookupName=git-for-windows/git
RUN install-tool git v2.35.1.windows.2

# Define the entry point for the docker container.
#CMD ["pwsh"]
