# escape=`

# Use the latest Windows Server Core image with .NET Framework 4.7.2.
FROM mcr.microsoft.com/windows/servercore:ltsc2019@sha256:46b40e526196d42b78d6bc777529203fd51467b095ddcb7acc87fc475c3c5e55

LABEL maintainer="Michael Kriese <michael.kriese@visualon.de>" `
  org.opencontainers.image.authors="VisualOn GmbH <code@visualon.de>" `
  org.opencontainers.image.source="https://github.com/visualon/docker-buildpack" `
  org.opencontainers.image.url="https://github.com/visualon/docker-buildpack"

ENV `
  POWERSHELL_TELEMETRY_OPTOUT=1 `
  DOTNET_CLI_TELEMETRY_OPTOUT=1 `
  DOTNET_CLI_UI_LANGUAGE=en-us `
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1

COPY src\ c:\

RUN c:\tools\init.cmd

# renovate: datasource=github-releases packageName=kiennq/scoop-better-shimexe
RUN install-tool shim 2.2.1

# renovate: datasource=github-releases packageName=git-for-windows/git
RUN install-tool git v2.39.2.windows.1

# Define the entry point for the docker container.
#CMD ["pwsh"]
