# escape=`

# Use the latest Windows Server Core image with .NET Framework 4.8.
FROM mcr.microsoft.com/windows/servercore:ltsc2025@sha256:7404f9a26420caf446b117b0bab158dd0ec45a0b4eb73a345137c33f20125094

LABEL maintainer="Michael Kriese <michael.kriese@visualon.de>" `
  org.opencontainers.image.authors="VisualOn GmbH <code@visualon.de>" `
  org.opencontainers.image.source="https://github.com/visualon/docker-buildpack" `
  org.opencontainers.image.url="https://github.com/visualon/docker-buildpack"

ENV `
  POWERSHELL_TELEMETRY_OPTOUT=1 `
  DOTNET_CLI_TELEMETRY_OPTOUT=1 `
  DOTNET_CLI_UI_LANGUAGE=en-us `
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1

COPY src\ c:\

RUN c:\tools\init.cmd

# renovate: datasource=github-releases packageName=kiennq/scoop-better-shimexe
RUN install-tool shim 2.2.1

# renovate: datasource=github-releases packageName=git-for-windows/git
RUN install-tool git v2.52.0.windows.1

RUN install-tool vc-redist 14

# Define the entry point for the docker container.
#CMD ["pwsh"]
