# escape=`

# Use the latest Windows Server Core image with .NET Framework 4.8.
FROM mcr.microsoft.com/windows/servercore:ltsc2022@sha256:7a755066b33150c44ab196118e84a070df556bcaeccb08818d1993eb3a37a6b8

LABEL maintainer="Michael Kriese <michael.kriese@visualon.de>" `
  org.opencontainers.image.authors="Michael Kriese <michael.kriese@visualon.de>" `
  org.opencontainers.image.source="https://github.com/visualon/docker-buildpack" `
  org.opencontainers.image.url="https://github.com/visualon/docker-buildpack"

ENV `
  POWERSHELL_TELEMETRY_OPTOUT=1 `
  DOTNET_CLI_TELEMETRY_OPTOUT=1 `
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1

COPY src\ c:\

RUN c:\tools\init.cmd

# renovate: datasource=github-releases lookupName=kiennq/scoop-better-shimexe versioning=gradle
RUN install-tool shim 2.2.1

# renovate: datasource=github-releases lookupName=git-for-windows/git
RUN install-tool git v2.33.1.windows.1

# Define the entry point for the docker container.
CMD ["pwsh"]
